# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends usage stats to help guide CocoaPods development.
# To prevent sending stats, uncomment the line below.
# cocoapods_stats = false

source 'https://github.com/CocoaPods/Specs.git'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
